Integrate FPL v2
FHIR/FSHOnline pull request #195
Opened 2024-12-31 18:42 UTC by jafeltra

_Note: This PR is in marked as a draft because the `FSHHelpers.test.jss` suite does not run yet but the general approach to integrating FPL v2 and new SUSHI and GoFSH is stable._

**Description:**
This PR updates FSH Online to use the new FPL v2 and newer versions of SUSHI and GoFSH that use FPL v2 as well.

This PR cleans up a good amount of code that was moved into FPL. I also tried to use some newer SUSHI functions where possible, rather than having FSH Online write its own versions.

The way I had to create to make some temporary definitions for GoFSH is a little odd, but it was the only way I could figure out how to use a FHIRProcessor to `processConfig` to get all the dependencies from an IG resource, which we needed to properly initialize the BrowserBasedPackageCache.

Note the following changes still need to be made to this branch before it can be merged:

- The `FSHHelpers.test.js` file cannot load the `sql-wasm.wasm` file correctly right now, so that needs to be figured out. The `assetsInclude` configuration field is what makes this work when running a development or production server, so I guess the testing equivalent needs to be figured out.
- Once the FSHHelpers.test.js file properly loads, the tests need to be updated to mock out the pieces that FPL is doing now, because it still is mocking out parts from the old FSH Online Processing functions, which do not exist anymore.
- The correct SUSHI and GoFSH versions need to be update din the TopBar component.

**Testing Instructions:**
For now, try using this locally in your browser to make sure there isn't functionality that I've missed that needs to be added in FPL or here. You should be able to:

- download and cache packages in your browser's IndexedDB -- you can clear your IndexedDB to ensure new packages are being downloaded, but also the default name of the database has changed, so the first time you run this, it should try to download and cache the package
- load packages from the cache if they're already downloaded
- run SUSHI without configured dependencies and with one or more configured dependencies
- run GoFSH without configured dependencies, with one or more configured dependencies, and with dependencies that are only specified in an ImplementationGuide resources

**Related Issue:**
N/A

2025-01-15 22:53 UTC, cmoesel requested changes
I'm so glad this is working! Thank you! I left two comments about possible places we could extract functions to make the code a little cleaner. Let me know what you think!

2025-01-20 01:45 UTC, jafeltra commented
@cmoesel - [65adeb5](https://github.com/FHIR/FSHOnline/pull/195/commits/65adeb50388c7e8191785f87f8c2aa0e863f81a4) pulled out the code for loading the FHIRDefinitions into a separate function and calls that function for SUSHI and GoFSH. I did have to add a little bit of specialized logic because the configuration that the GoFSH `loadExternalDependencies` uses is a different type than the configuration than the SUSHI `loadExternalDependencies`. Let me know what you think. If you don't like it, it's fine by me if you revert it. That commit also pulls out the code that had to set up temp variables just to determine the GoFSH configuration into a separate function, which kind of hides its weirdness.

One thing I just noticed is that there's an error when GoFSH is run before SUSHI. This is because GoFSH is setting up a LakeOfFhir:

```javascript
const lake = new processor.LakeOfFHIR(docs);
await lake.prepareDefs();
```
However, the FHIRDefinitions that LakeOfFHIR uses at that point is uninitialized, so it tries to initialize it, but the FHIRDefinitions is made with the default packageDB and there's no way to provide the needed override to use the `locateFile` option. I didn't have a chance to look too much into fixing it, but I think it might require an update to GoFSH, which is a little unfortunate. Maybe there's another way around it though. It probably is best to not merge this until that is fixed though.

2025-02-04 22:39 UTC, jafeltra commented
@cmoesel - I think this is ready for review!

[65adeb5](https://github.com/FHIR/FSHOnline/pull/195/commits/65adeb50388c7e8191785f87f8c2aa0e863f81a4) - pulls out the code for loading the FHIRDefinitions into a separate function and calls that function for SUSHI and GoFSH. I did have to add a little bit of specialized logic because the configuration that the GoFSH loadExternalDependencies uses is a different type than the configuration than the SUSHI loadExternalDependencies. Let me know what you think. If you don't like it, it's fine by me if you revert it. That commit also pulls out the code that had to set up temp variables just to determine the GoFSH configuration into a separate function, which kind of hides its weirdness.

[e0ace2a](https://github.com/FHIR/FSHOnline/pull/195/commits/e0ace2a0abca8d84cd7fd6bed945fc18389ef4bb) - initializes sql.js once for SUSHI and once for GoFSH so it is already properly initialized for any other places that use it. That means we don't need the`locateFile` override, but that's okay.

[1c217a9](https://github.com/FHIR/FSHOnline/pull/195/commits/1c217a940b6b1d636e9a8dea869c71af4742867d) - filters out any provided dependency that doesn't have a version. That makes it so if anyone has a typo in the configuration modal (like `hl7.fhir.us.core@6.0.0` instead of `hl7.fhir.us.core#6.0.0`), FSH Online continues running and doesn't try to load that dependency, since it would break later down the line without a version.

2025-02-05 15:03 UTC, cmoesel requested changes
This looks good. I have one request. Let me know if it is non-trivial.

2025-02-06 16:32 UTC, jafeltra commented on src/utils/helpers.js
> +        return;
[df0e817](https://github.com/FHIR/FSHOnline/pull/195/commits/df0e817854b24ca3669d118564a1048a713190af) - I reworked where the filtering happens to more easily and consistently log a warning. GoFSH handles dependencies in the wrong format better, but I also added the same filtering in for GoFSH so the logged warning was consistent. Let me know what you think.

2025-02-06 17:17 UTC, jafeltra commented on src/utils/helpers.js
> +        return;
Unfortunately, yes that's expected. It's because GoFSH (for whatever legacy reason) replaces all the `#` with `@` and then splits on the `@` symbol. So when `hl7.fhir.us.core@6.0.0` gets passed into GoFSH, it actually is fine with that. The filtering in [df0e817](https://github.com/FHIR/FSHOnline/pull/195/commits/df0e817854b24ca3669d118564a1048a713190af) happens after GoFSH has processed and built a configuration for us, so it already knew how to properly handle `hl7.fhir.us.core@6.0.0`. This behavior is actually consistent with what happens on the deployed version now -- you'll get a warning that FSH Online used to log (it got removed in this branch) that it couldn't load `hl7.fhir.us.core@6.0.0#undefined` when converting FSH to FHIR, but you'll get no issues when converting FHIR to FSH.

But just because that's how it works now, doesn't mean this is how it has to work going forward, so let me know if you'd prefer I update it here.

2025-02-06 17:51 UTC, cmoesel commented on src/utils/helpers.js
> +        return;
I think I just misinterpreted this by thinking "more consistent" meant the same error in both cases:
> GoFSH handles dependencies in the wrong format better, but I also added the same filtering in for GoFSH so the logged warning was consistent. 

I think it's probably fine. I don't think it's worth adding additional complication to try to "fix" it.

2025-02-06 17:53 UTC, cmoesel approved these changes
This looks good! Thank you, @jafeltra. You've now proven that the FPL browser-based implementations work -- and you've unstuck us from that prior version of SUSHI. Thanks!

2025-02-06 17:54 UTC, jafeltra commented on src/utils/helpers.js
> +        return;
> I think I just misinterpreted this by thinking "consistent" meant the same warning in both cases

I guess that statement should really have said:

> GoFSH handles dependencies in the wrong format better, but I also added the same filtering in for GoFSH so the logged warning was consistent*.
>
> *consistent in all cases except for when you mistype and use `@` instead of `#`.

2025-02-06 19:03 UTC, merged